file:
  directory: D:/ksj/download/greengram_Tdd

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3_test
    username: root
    password: green502
  sql:
    init:
      mode: never