const:
  default-page-size: 20

file:
  directory: D:/ksj/download/greengramjpa


jwt:
  issuer: green@green.kr #아무거나 써도 됨
  secret-key: DaeguGreenComputerAcademysmdfajlsfjlaskfjlaskdienvoinxovkaodlvikasjofiajsoidkjrfoeaiwjfoiwjifhgurhgcmlskdjfwqrerdsaf

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_jpa
    username: root
    password: green502
  jackson:
    default-property-inclusion: non_null  #응답 JSON을 만들때 null인 속성은 제외한다.
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create #entity를 서버 기동때마다 drop 후 create한다.
      #ddl-auto: update  #entity가 없으면 create, 기존에 존재하는 것은 컬럼을 새롭게 추가하는 것만 반영.
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true #로그 찍을 때 보기 편하게 포맷팅 #출력을 보기 편하게
        order_updates: true #JPA Batch 작업 , 모았다가 한번에 작업하는 것.
    show-sql: true #JPA가 만든 쿼리문 로그에 출력

  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
