const:
  default-page-size: 20

file:
  directory: D:/ksj/download/greengramSecurity


jwt:
  issuer: green@green.kr #아무거나 써도 됨
  secret-key: DaeguGreenComputerAcademysmdfajlsfjlaskfjlaskdienvoinxovkaodlvikasjofiajsoidkjrfoeaiwjfoiwjifhgurhgcmlskdjfwqrerdsaf

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
  jackson:
    default-property-inclusion: non_null  #응답 JSON을 만들때 null인 속성은 제외한다.
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
